name: quality controls
run-name: run quality controls
on: [push, workflow_dispatch]
jobs:
  Run-Quality-Controls:
    runs-on: ubuntu-latest
    steps:
      - name: Print information about the run
        run: |
          echo "Platform is ${{ runner.os }}"
          echo "Repository is ${{ github.repository }}"
          echo "Branch is ${{ github.ref }}"
      - name: Clone repository
        uses: actions/checkout@v4
        with:
          persist-credentials: false
      - name: Prepare Python environment
        uses: actions/setup-python@v5
        with:
          python-version: '3.x'
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
          pip install pytest
      - name: Run unit tests
        run: pytest ${{ github.workspace }}/tests
      - name: Print concluding information
        run: echo "Job status is ${{ job.status }}"
