name: quality controls
run-name: run quality controls
on: [push, workflow_dispatch]
jobs:
  Run-Quality-Controls:
    runs-on: ubuntu-latest
    steps:
      - name: Clone repository
        uses: actions/checkout@v4
        with:
          persist-credentials: false
      - name: Prepare Python environment
        uses: actions/setup-python@v5
        with:
          python-version: '3.x'
      - name: Install required Python packages
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
      - name: Run linter
        run: |
          pip install black
          black --check --diff --color ${{ github.workspace }}/geomodeloutputs
          black --check --diff --color ${{ github.workspace }}/tests/test_*
      - name: Run unit tests
        run: |
          pip install pytest
          pytest ${{ github.workspace }}/tests
