name: quality controls
run-name: run quality controls
on: [push, workflow_dispatch]
jobs:
  Run-Quality-Controls:
    runs-on: ubuntu-latest
    steps:
      - run: echo "Platform is ${{ runner.os }}"
      - run: echo "Repository is ${{ github.repository }}"
      - run: echo "Branch is ${{ github.ref }}"
      - uses: actions/checkout@v4
        with:
          persist-credentials: false
      - uses: actions/setup-python@v5
        with:
          python-version: '3.x'
      - run: python -m pip install --upgrade pip
      - run: pip install pytest
      - run: pytest ${{ github.workspace }}/tests
      - run: echo "Job status is ${{ job.status }}"
