name: quality controls
run-name: run quality controls
jobs:
  Run-Quality-Controls:
    runs-on: ubuntu-latest
    steps:
      - run: echo "Platform: ${{ runner.os }}"
      - run: echo "Repository: ${{ github.repository }}"
      - run: echo "Branch: ${{ github.ref }}"
      - run: echo "Job status: ${{ job.status }}"
      - uses: actions/checkout@v4
        with:
          persist-credentials: false
